name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/setup-go@v4
        with:
          go-version: ^1.24
        id: go

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: go build -v -ldflags "-X main.versionString=snapshot-$GITHUB_SHA"
      
      - name: Build macOS
        run: GOOS=darwin GOARCH=amd64 go build -v -ldflags "-X main.versionString=snapshot-$GITHUB_SHA"

      - name: Build Windows
        run: GOOS=windows GOARCH=amd64 go build -v -ldflags "-X main.versionString=snapshot-$GITHUB_SHA"

      - name: Test
        run: go test -v ./...
