// Code generated by "stringer -type=ExpressionType"; DO NOT EDIT.

package csql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExpressionNop-0]
	_ = x[ExpressionOperator-1]
	_ = x[ExpressionLiteral-2]
	_ = x[ExpressionColumnReference-3]
}

const _ExpressionType_name = "ExpressionNopExpressionOperatorExpressionLiteralExpressionColumnReference"

var _ExpressionType_index = [...]uint8{0, 13, 31, 48, 73}

func (i ExpressionType) String() string {
	if i < 0 || i >= ExpressionType(len(_ExpressionType_index)-1) {
		return "ExpressionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExpressionType_name[_ExpressionType_index[i]:_ExpressionType_index[i+1]]
}
