// Code generated by "stringer -type=ValueType"; DO NOT EDIT.

package csql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ValueTypeUnknown-0]
	_ = x[ValueTypeString-1]
	_ = x[ValueTypeBool-2]
	_ = x[ValueTypeInt-3]
	_ = x[ValueTypeDouble-4]
	_ = x[ValueTypeDate-5]
}

const _ValueType_name = "ValueTypeUnknownValueTypeStringValueTypeBoolValueTypeIntValueTypeDoubleValueTypeDate"

var _ValueType_index = [...]uint8{0, 16, 31, 44, 56, 71, 84}

func (i ValueType) String() string {
	if i < 0 || i >= ValueType(len(_ValueType_index)-1) {
		return "ValueType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValueType_name[_ValueType_index[i]:_ValueType_index[i+1]]
}
